import { makeStyles } from '@mui/styles/index.js';

export default makeStyles((theme) => ({
    mainContainer: {
        position: 'fixed !important',
        width: '80% !important',
        alignSelf: 'center !important',
        left: '50% !important',
        overflow: 'auto !important',
        transform: 'translate(-50%, 0%) !important',
        zIndex: '51 !important',
        height: 'calc(100%) !important',
        [theme.breakpoints.down('md')]: {
            width: '90% !important',
        },
    },
    overlay: {
        position: 'fixed !important',
        left: '0 !important',
        top: '0 !important',
        width: '100vw !important',
        height: '100% !important',
        minHeight: '100vh !important',
        backgroundColor: '#e2e2e2 !important',
        opacity: '0.8 !important',
        zIndex: '50 !important',
    },
    overlay2: {
        position: 'absolute !important',
        height: '100% !important',
        display: 'none !important',
        width: '100% !important',
        backgroundColor: '#e2e2e2 !important',
        opacity: '0.6 !important',
        zIndex: '50 !important',
    },
    profile: {
        margin: 'auto !important',
        marginTop: '80px !important',
        marginBottom: '20px !important',
        width: '98% !important',
        display: 'flex !important',
        flexDirection: 'column !important',
        boxShadow: '0px 0px 8px #aaaaaa !important',
    },
    avatar: {
        width: '15vw !important',
        height: '15vw !important',
        backgroundColor: '#e2e2e2 !important',
        minHeight: '80px !important',
        minWidth: '80px !important',
        maxHeight: '200px !important',
        maxWidth: '200px !important',
        border: '2px solid #cccccc !important',
    },
    username: {
        position: 'absolute !important',
        fontFamily: 'Cabin !important',
        fontSize: '30px !important',
        fontWeight: '500 !important',
        color: '#282828 !important',
        top: '70% !important',
        left: '100% !important',
        letterSpacing: '2px !important',
        marginLeft: '16px !important',
        transform: 'translate(0%,00%) !important',
        [theme.breakpoints.down('sm')]: {
            textShadow: '0px 1px 6px #e2e2e2 !important',
            fontSize: '26px !important',
            letterSpacing: '1.6px !important',
        },
        [theme.breakpoints.down('xs')]: {
            textShadow: '0px 1px 4px #e2e2e2 !important',
            marginLeft: '8px !important',
            fontSize: '22px !important',
            letterSpacing: '1.4px !important',
        },
    },
    cover: {
        position: 'relative !important',
        top: '0 !important',
        left: '0 !important',
        backgroundColor: '#e2e2e2 !important',
        width: '100% !important',
        height: '35vw !important',
        borderRadius: '4px !important',
        border: '1px solid #cccccc !important',
        minHeight: '100px !important',
        boxSizing: 'border-box !important',
        display: 'flex !important',
        alignItems: 'flex-start !important',
        [theme.breakpoints.down('sm')]: {
            height: '40vw !important',
            fontSize: '25vh !important',
        },
        [theme.breakpoints.down('xs')]: {
            fontSize: '20vh !important',
        },
    },
    coverImg: {
        borderRadius: '4px !important',
        width: '100% !important',
        backgroundColor: '#e2e2e2 !important',
        height: '100% !important',
        objectFit: 'cover !important',
    },
    editBtn: {
        float: 'right !important',
        fontSize: '14px !important',
        display: 'inline !important',
        color: '#888888 !important',
        cursor: 'pointer !important',
        marginRight: '10px !important',
    },
    container: {
        top: '100% !important',
        left: '2vw !important',
        position: 'absolute !important',
        display: 'flex !important',
        alignItems: 'flex-end !important',
        transform: 'translate(0%,-70%) !important',
    },
    info: {
        display: 'flex !important',
        width: '100% !important',
        boxSizing: 'border-box !important',
        border: '1px solid #cccccc !important',
        borderRadius: '4px !important',
        paddingBottom: '10px !important',
        backgroundColor: '#e8e8e8 !important',
        [theme.breakpoints.down('sm')]: {
            flexDirection: 'column !important',
        },
    },
    mainInfo: {
        display: 'flex !important',
        flexDirection: 'column !important',
        padding: '4px 8px !important',
        width: '30% !important',
        boxSizing: 'border-box !important',
        [theme.breakpoints.down('sm')]: {
            width: '100% !important',
        },
        [theme.breakpoints.down('xs')]: {
            padding: '4px 4px !important',
        },
    },
    otherInfo: {
        display: 'flex !important',
        width: '70% !important',
        flexDirection: 'column !important',
        padding: '4px 8px !important',
        boxSizing: 'border-box !important',
        [theme.breakpoints.down('sm')]: {
            width: '100% !important',
        },
        [theme.breakpoints.down('xs')]: {
            padding: '4px 4px !important',
        },
    },
    space: {
        height: '5vw !important',
        width: '100% !important',
        backgroundColor: '#e2e2e2 !important',
        [theme.breakpoints.down('sm')]: {
            height: '7vw !important',
        },
        [theme.breakpoints.down('xs')]: {
            height: '12vw !important',
        },
    },
    heading: {
        padding: '6px !important',
        fontWeight: '500 !important',
        color: '#282828 !important',
        boxSizing: 'border-box !important',
        fontSize: '15px !important',
        paddingLeft: '16px !important',
        [theme.breakpoints.down('xs')]: {
            fontSize: '14px !important',
        },
    },
    content: {
        boxSizing: 'border-box !important',
        fontSize: '15px !important',
        height: 'fit-content !important',
        minHeight: '30px !important',
        margin: '4px 12px 8px 12px !important',
        border: '1px solid #cccccc !important',
        borderRadius: '4px !important',
        padding: '6px 10px !important',
        color: '#383838 !important',
        letterSpacing: '0.4px !important',
        display: 'flex !important',
        flexDirection: 'column !important',
        backgroundColor: '#f2f2f2 !important',
        overflowY: 'scroll !important',
        [theme.breakpoints.down('xs')]: {
            fontSize: '14px !important',
        },
    },
    aboutMe: {
        flexGrow: '1 !important',
        color: '#484848 !important',
        minHeight: '150px !important',
        margin: '4px 12px 8px 12px !important',
        wordWrap: 'break-word !important',
        overflowY: 'auto !important',
        whiteSpace: 'pre-line !important',
    },
    infoCouple: {
        display: 'flex !important',
        flexDirection: 'column !important',
        [theme.breakpoints.down('sm')]: {
            flexDirection: 'column !important',
        },
    },
    infoItem: {
        width: '100% !important',
        padding: '2px 0px !important',
        [theme.breakpoints.down('sm')]: {
            width: '100% !important',
        },
    },
    statusDiv: {
        padding: '2px 0px !important',
    },
    aboutDiv: {
        flexGrow: '1 !important',
        display: 'flex !important',
        flexDirection: 'column !important',
        padding: '2px 0px !important',
    },
    noProfile: {
        position: 'absolute !important',
        top: '50% !important',
        left: '50% !important',
        fontSize: '26px !important',
        letterSpacing: '0.6px !important',
        fontWeight: '500 !important',
        color: '#585858 !important',
        transform: 'translate(-50%, -50%) !important',
        boxSizing: 'border-box !important',
        height: '80px !important',
        width: '300px !important',
        border: '1px solid #cccccc !important',
        display: 'flex !important',
        zIndex: '10 !important',
        alignItems: 'center !important',
        justifyContent: 'center !important',
        maxWidth: '50% !important',
        backgroundColor: '#e2e2e2 !important',
        [theme.breakpoints.down('xs')]: {
            width: '150px !important',
            fontSize: '18px !important',
            height: '40px !important',
        },
    },
    editAvatarDiv: {
        position: 'absolute !important',
        top: '0% !important',
        left: '60% !important',
        height: '26px !important',
        width: '60px !important',
        zIndex: '2 !important',
        backgroundColor: '#e2e2e2 !important',
        border: '1px solid #aaaaaa !important',
        opacity: '0.8 !important',
        display: 'flex !important',
        alignItems: 'center !important',
        justifyContent: 'space-around !important',
        fontSize: '20px !important',
        borderRadius: '4px !important',
        [theme.breakpoints.down('xs')]: {
            height: '22px !important',
            width: '50px !important',
            fontSize: '16px !important',
        },
    },
    editCoverDiv: {
        position: 'absolute !important',
        bottom: '0% !important',
        right: '0% !important',
        height: '26px !important',
        borderRadius: '4px !important',
        width: '60px !important',
        border: '1px solid #aaaaaa !important',
        zIndex: '2 !important',
        backgroundColor: '#e2e2e2 !important',
        opacity: '0.8 !important',
        display: 'flex !important',
        alignItems: 'center !important',
        justifyContent: 'space-around !important',
        fontSize: '20px !important',
        [theme.breakpoints.down('xs')]: {
            height: '22px !important',
            width: '50px !important',
            fontSize: '16px !important',
        },
    },
    imageIcon: {
        color: '#686868 !important',
        '&:hover': {
            cursor: 'pointer !important',
            transform: 'scale(1.1,1.1) !important',
        },
    },
    closeProfileBtn: {
        position: 'absolute !important',
        top: '0% !important',
        right: '0% !important',
        display: 'flex !important',
        alignItems: 'center !important',
        backgroundColor: '#e2e2e2 !important',
        borderRadius: '4px !important',
        boxSizing: 'border-box !important',
        opacity: '0.6 !important',
    },
    closeIcon: {
        fontSize: '30px !important',
        padding: '6px 10px !important',
        color: '#888888 !important',
        textShadow: '0px 0px 2px #e2e2e2 !important',
        '&:hover': {
            cursor: 'pointer !important',
            transform: 'scale(1.1,1.1) !important',
        },
        [theme.breakpoints.down('xs')]: {
            fontSize: '24px !important',
            padding: '2px 6px !important',
        },
    },
    zoomCoverDiv: {
        display: 'none !important',
        position: 'absolute !important',
        width: '96% !important',
        maxHeight: '70vh !important',
        overflow: 'hidden !important',
        left: '50% !important',
        alignItems: 'center !important',
        boxSizing: 'border-box !important',
        transform: 'translate(-50%,-50%) !important',
        boxShadow: '0px 0px 8px #888888 !important',
        zIndex: '100 !important',
        border: '6px solid #e2e2e2 !important',
        borderRadius: '4px !important',
    },
    zoomAvatarDiv: {
        display: 'none !important',
        position: 'absolute !important',
        width: '50vw !important',
        overflow: 'hidden !important',
        height: '50vw !important',
        boxSizing: 'border-box !important',
        boxShadow: '0px 0px 8px #888888 !important',
        left: '50% !important',
        transform: 'translate(-50%,-50%) !important',
        minWidth: '200px !important',
        maxWidth: '250px !important',
        minHeight: '200px !important',
        maxHeight: '250px !important',
        zIndex: '100 !important',
        border: '6px solid #e2e2e2 !important',
        borderRadius: '4px !important',
    },
    zoomCover: {
        width: '100% !important',
        objectFit: 'cover !important',
    },
    zoomAvatar: {
        width: '100% !important',
        objectFit: 'cover !important',
    },
    coverProgressDiv: {
        position: 'absolute !important',
        width: '200px !important',
        left: '50% !important',
        top: '50% !important',
        zIndex: '20 !important',
        maxWidth: '40% !important',
        transform: 'translate(-50%,-50%) !important',
        maxWidth: '80% !important',
        [theme.breakpoints.down('sm')]: {
            width: '140px !important',
        },
    },
    imageProgressDiv: {
        position: 'absolute !important',
        width: '100px !important',
        zIndex: '20 !important',
        left: '50% !important',
        top: '50% !important',
        transform: 'translate(-50%,-50%) !important',
        maxWidth: '80% !important',
        [theme.breakpoints.down('sm')]: {
            width: '60px !important',
        },
    },
}));
