import { makeStyles } from '@mui/styles/index.js';

export default makeStyles((theme) => ({
    mainContainer: {
        height: '100% !important',
        width: '100% !important',
        backgroundColor: '#cccccc !important',
        display: 'flex !important',
        flexDirection: 'column !important',
        overflow: 'hidden !important',
        borderRadius: '4px !important',
    },
    chatWrap: {
        overflowY: 'auto !important',
        overflowX: 'hidden !important',
    },
    chatItem: {
        backgroundColor: '#f2f2f2 !important',
        margin: '8px 0px !important',
        padding: '2px !important',
        boxSizing: 'border-box !important',
        width: '100% !important',
        display: 'flex !important',
        alignItems: 'flex-start !important',
        [theme.breakpoints.down('xs')]: {
            padding: '2px 0px !important',
        },
    },
    chatItemDetail: {
        display: 'flex !important',
        alignItems: 'center !important',
        fontWeight: '400 !important',
        margin: '4px 0px 4px 0px !important',
        letterSpacing: '0.6px !important',
        width: '100% !important',
        justifyContent: 'space-between !important',
    },
    chatItemAvatar: {
        height: '34px !important',
        width: '34px !important',
        backgroundColor: '#e2e2e2 !important',
        borderRadius: '20px !important',
        border: '2px solid #cccccc !important',
        margin: '4px 4px !important',
        objectFit: 'cover !important',
        '&:hover': {
            cursor: 'pointer !important',
        },
    },
    content: {
        width: 'calc(100% - 50px) !important',
        display: 'flex !important',
        backgroundColor: '#f2f2f2 !important',
        flexDirection: 'column !important',
        padding: '4px 2px 4px 2px !important',
    },
    chatItemUser: {
        color: '#585858 !important',
        fontSize: '15px !important',
        letterSpacing: '0.4px !important',
        marginLeft: '4px !important',
        fontWeight: '600 !important',
        overflow: 'hidden !important',
        [theme.breakpoints.down('xs')]: {
            fontWeight: '500 !important',
            fontSize: '13px !important',
            marginLeft: '0px !important',
        },
    },
    chatItemTime: {
        marginRight: '6px !important',
        fontSize: '13px !important',
        color: '#888888 !important',
        alignSelf: 'stretch !important',
        [theme.breakpoints.down('xs')]: {
            fontSize: '11px !important',
            marginRight: '4px !important',
        },
    },
    chatItemMsg: {
        fontFamily: 'Bai Jamjuree !important',
        letterSpacing: '0.4px !important',
        width: '100% !important',
        alignItems: 'center !important',
        boxSizing: 'border-box !important',
        padding: '2px 4px 4px 4px !important',
        overflowWrap: 'break-word !important',
        backgroundColor: '#f2f2f2 !important',
        fontSize: '16px !important',
        [theme.breakpoints.down('xs')]: {
            fontSize: '13px !important',
            paddingLeft: '0px !important',
            paddingRight: '0px !important',
        },
    },
    chatItemBox: {
        height: '100% !important',
        width: '100% !important',
        backgroundColor: '#e8e8e8 !important',
        display: 'flex !important',
        boxSizing: 'border-box !important',
        flexDirection: 'column !important',
        overflowY: 'auto !important',
        justifyContent: 'flex-end !important',
    },
    header: {
        padding: '5px !important',
        boxSizing: 'border-box !important',
    },
    footer: {
        height: '60px !important',
        width: '100% !important',
        backgroundColor: '#cccccc !important',
        display: 'flex !important',
        alignItems: 'center !important',
    },
    usericon: {
        fontSize: '22px !important',
        color: '#282828 !important',
        float: 'right !important',
        '&:hover': {
            cursor: 'pointer !important',
        }
    },
    sendicon: {
        fontSize: '35px !important',
        color: '#282828 !important',
        '&:hover': {
            cursor: 'pointer !important',
        },
        padding: '0px 4px !important',
        userSelect: 'none !important',
    },
    chatInput: {
        margin: '0px 4px 0px 8px !important',
        fontSize: '16px !important',
        width: '100% !important',
        border: '1px solid #aaaaaa !important',
        boxSizing: 'border-box !important',
        padding: '0px 8px !important',
        height: '70% !important',
        borderRadius: '8px !important',
        backgroundColor: '#eeeeee !important',
        '&:focus': {
            outline: 'none !important',
        },
        [theme.breakpoints.down('xs')]: {
            fontSize: '14px !important',
        },
    },
    userList: {
        position: 'absolute !important',
        left: '95% !important',
        overflowY: 'scroll !important',
        transform: 'translate(-100%, 0%) !important',
        width: '250px !important',
        maxWidth: '70% !important',
        backgroundColor: '#f8f8f8 !important',
        display: 'none !important',
        fontSize: '15px !important',
        letterSpacing: '0.2px !important',
    },
    userListItem: {
        width: '100% !important',
        height: '56px !important',
        borderBottom: '2px solid #e2e2e2 !important',
        boxSizing: 'border-box !important',
        alignItems: 'center !important',
        display: 'flex !important',
        flexDirection: 'row !important',
        '&:hover': {
            cursor: 'pointer !important',
        },
    },
    userListAvatar: {
        height: '30px !important',
        width: '30px !important',
        objectFit: 'cover !important',
        borderRadius: '17px !important',
        margin: '0px 8px !important',
        border: '2px solid #cccccc !important',
    },
    userListName: {
        flexGrow: "1 !important",
        textOverflow: 'ellipsis !important',
        whiteSpace: 'nowrap !important',
        overflow: 'hidden !important',
        fontWeight: '500 !important',
        color: '#333333 !important',
        letterSpacing: '0.3px !important',
        [theme.breakpoints.down('xs')]: {
            fontSize: '14px !important',
        },
    },
    startContainer: {
        position: 'relative !important',
        width: '100% !important',
        height: '100% !important',
        color: '#282828 !important',
        backgroundColor: '#e8e8e8 !important',
        borderRadius: '4px !important',
        overflowY: 'auto !important',
        boxSizing: 'border-box !important',
    },
    startType: {
        position: 'relative !important',
        width: '100% !important',
        display: 'flex !important',
        flexDirection: 'column !important',
        flexWrap: 'wrap !important',
        boxSizing: 'border-box !important',
        padding: '20px 0px !important',
    },
    startHeading: {
        width: '100% !important',
        fontWeight: '600 !important',
        letterSpacing: '1px !important',
        fontSize: '30px !important',
        padding: '0px 20px !important',
        color: '#282828 !important',
        boxSizing: 'border-box !important',
        marginBottom: '10px !important',
        [theme.breakpoints.down('sm')]: {
            padding: '0px 10px !important', 
        },
    },
    startDescription: {
        width: '100% !important',
        height: 'fit-content !important',
        padding: '4px 16px !important',
        boxSizing: 'border-box !important',
        borderRadius: '4px !important',
        color: '#505050 !important',
        fontSize: '14px !important',
        lineHeight: '1.4 !important',
        letterSpacing: '0.2px !important',
        [theme.breakpoints.down('sm')]: {
            padding: '4px 8px !important',
        },
    },
    textCenter: {
        padding: '40px 10px !important',
        boxSizing: 'border-box !important',
        width: '100% !important',
        fontWeight: '500 !important',
        textAlign: 'center !important',
        color: '#282828 !important',
    },
    formJoin: {
        width: 'fit-content !important',
        margin: '0px auto !important',
        display: 'flex !important',
        flexDirection: 'column !important',
        boxSizing: 'border-box !important',
        alignItems: 'center !important',
    },
    buttonRoom: {
        letterSpacing: '0.5px !important',
        marginTop: '16px !important',
        '&:hover': {
            backgroundColor: '#282828 !important',
            color: '#e2e2e2 !important',
        }
    },
    inputDiv: {
        display: 'flex !important',
        flexDirection: 'column !important',
        height: '80px !important',
        justifyContent: 'space-around !important',
        [theme.breakpoints.down('xs')]: {
            //flexDirection: 'column',
        },
    },
    checkbox: {
        margin: '2px 8px 0px 8px !important',
        [theme.breakpoints.down('xs')]: {
            margin: '2px 0px 0px -10px !important',
        },
    },
    formContainer: {
        display: 'flex !important',
        alignItems: 'flex-end !important',
        paddingLeft: '10px !important',
        [theme.breakpoints.down('xs')]: {
            flexDirection: 'column !important',
            alignItems: 'flex-start !important',
        },
    },
}));
