import { makeStyles } from '@mui/styles/index.js';

export default makeStyles((theme) => ({
    mainContainer: {
        position: 'relative !important',
        top: '0 !important',
        left: '0 !important',
        width: '100vw !important',
        height: '100% !important',
        color: '#282828 !important',
        backgroundColor: '#e2e2e2 !important',
    },
    topDiv: {
        position: 'relative !important',
        backgroundColor: '#282828 !important',
        marginTop: '63px !important',
        width: '100vw !important',
        height: `calc(100% - 63px) !important`,
        [theme.breakpoints.down('xs')]: {
            marginTop: '55px !important',
            height: `calc(100% - 55px) !important`,
        },
    },
    coverFrame: {
        width: '100% !important',
        border: 'none !important',
        borderWidth: '0px !important',
        height: '100% !important',
    },
    content: {
        position: 'absolute !important',
        width: '60% !important',
        height: `calc(${window.innerHeight}px - 180px) !important`,
        top: '0 !important',
        left: '0 !important',
        zIndex: '2 !important',
        display: 'flex !important',
        flexDirection: 'column !important',
        justifyContent: 'center !important',
        [theme.breakpoints.down('md')]: {
            width: '70% !important',
        },
        [theme.breakpoints.down('sm')]: {
            width: '100% !important',
        },
    },
    phrase: {
        width: '80% !important',
        margin: '0px auto !important',
        fontSize: '78px !important',
        textAlign: 'center !important',
        lineHeight: '0.9 !important',
        letterSpacing: '0.4px !important',
        fontWeight: '700 !important',
        color: '#e2e2e2 !important',
        marginBottom: '50px !important',
        minWidth: '300px !important',
        [theme.breakpoints.down('md')]: {
            fontSize: '68px !important',
            marginBottom: '38px !important',
        },
        [theme.breakpoints.down('sm')]: {
            marginBottom: '28px !important',
            fontSize: '42px !important',
        },
    },
    login: {
        margin: '0px auto !important',
        maxWidth: '260px !important',
        display: 'flex !important',
        justifyContent: 'space-around !important',
        width: '90% !important',
    },
    desc: {
        margin: '0px auto !important',
        width: '70% !important',
        fontSize: '28px !important',
        color: '#aaaaaa !important',
        marginBottom: '50px !important',
        textAlign: 'center !important',
        letterSpacing: '0.6px !important',
        [theme.breakpoints.down('md')]: {
            letterSpacing: '0.5px !important',
            fontSize: '24px !important',
        },
        [theme.breakpoints.down('xs')]: {
            width: '80% !important',
            letterSpacing: '0.3px !important',
            fontSize: '20px !important',
        },
    },
    buttonSignUp: {
        color: '#282828 !important',
        fontSize: '16px !important',
        paddingLeft: '16px !important',
        paddingRight: '16px !important',
        letterSpacing: '1px !important',
        backgroundColor: '#e2e2e2 !important',
    },
    buttonLogin: {
        color: '#e2e2e2 !important',
        fontSize: '16px !important',
        letterSpacing: '1px !important',
        border: '2px solid #888888 !important',
        paddingLeft: '16px !important',
        paddingRight: '16px !important',
        '&:hover': {
            backgroundColor: '#e2e2e2 !important',
            border: '2px solid #e2e2e2 !important',
            color: '#282828 !important',
        },
    },
    secondDiv: {
        width: '100% !important',
        display: 'flex !important',
        flexDirection: 'column !important',
        alignItems: 'center !important',
        backgroundColor: '#e2e2e2 !important',
    },
    checkoutGames: {
        width: '90% !important',
    },
    heading: {
        width: '100% !important',
        textAlign: 'center !important',
        margin: '60px auto !important',
        fontSize: '56px !important',
        letterSpacing: '2px !important',
        fontWeight: '700 !important',
        color: '#282828 !important',
        [theme.breakpoints.down('md')]: {
            letterSpacing: '1px !important',
            fontSize: '48px !important',
            marginBottom: '50px !important',
        },
        [theme.breakpoints.down('sm')]: {
            letterSpacing: '0.4px !important',
            fontSize: '36px !important',
            marginBottom: '40px !important',
        },
    },
    checkoutWrap: {
        width: '100% !important',
        display: 'flex !important',
        flexDirection: 'column !important',
        alignItems: 'center !important',
    },
    checkoutCard: {
        marginBottom: '60px !important',
        width: '60% !important',
        display: 'flex !important',
        borderRadius: '6px !important',
        overflow: 'hidden !important',
        borderWidth: '1px !important',
        borderColor: '#aaaaaa !important',
        borderStyle: 'solid !important',
        [theme.breakpoints.down('md')]: {
            width: '80% !important',
            marginBottom: '50px !important',
        },
        [theme.breakpoints.down('sm')]: {
            flexDirection: 'column !important',
            width: '85% !important',
            marginBottom: '45px !important',
        },
        [theme.breakpoints.down('xs')]: {
            width: '100% !important',
            marginBottom: '40px !important',
        },
    },
    checkoutNameOuter: {
        position: 'relative !important',
        width: '30% !important',
        padding: '16px !important',
        textAlign: 'center !important',
        boxSizing: 'border-box !important',
        letterSpacing: '1.2px !important',
        fontSize: '30px !important',
        display: 'flex !important',
        flexDirection: 'column !important',
        alignItems: 'center !important',
        justifyContent: 'space-between !important',
        backgroundColor: '#282828 !important',
        color: '#cccccc !important',
        [theme.breakpoints.down('md')]: {
            letterSpacing: '1px !important',
            fontSize: '26px !important',
        },
        [theme.breakpoints.down('sm')]: {
            letterSpacing: '0.6px !important',
            fontSize: '22px !important',
            width: '100% !important',
        },
        [theme.breakpoints.down('xs')]: {
            letterSpacing: '0.4px !important',
            fontSize: '20px !important',
        },
    },
    checkoutGifDiv: {
        width: '70% !important',
        height: '70% !important',
        [theme.breakpoints.down('sm')]: {
            width: '100% !important',
        },
    },
    checkoutGif: {
        width: '100% !important',
        height: '100% !important',
    },
    checkoutBtn: {
        marginBottom: '20px !important',
        padding: '12px 20px !important',
        color: '#cccccc !important',
        letterSpacing: '0.6px !important',
        border: '2px solid #666666 !important',
        backgroundColor: '#282828 !important',
        '&:hover': {
            borderColor: '#aaaaaa !important',
        },
        [theme.breakpoints.down('sm')]: {
            marginBottom: '0px !important',
            padding: '8px 16px !important',
            marginTop: '20px !important',
        },
    },
}));
