import { makeStyles } from '@mui/styles/index.js';

export default makeStyles((theme) => ({
    mainDiv: {
        marginTop: '63px !important',
        height: 'fit-content !important',
        minHeight: 'calc(100vh - 63px) !important',
        boxSizing: 'border-box !important',
        color: '#282828 !important',
        backgroundColor: '#e2e2e2 !important',
        [theme.breakpoints.down('xs')]: {
            marginTop: '55px !important',
        },
    },
    container: {
        padding: '0px 3vw !important',
        paddingTop: '20px !important',
        boxSizing: 'border-box !important',
        backgroundColor: '#e2e2e2 !important',
        width: '100% !important',
        display: 'flex !important',
        justifyContent: 'center !important',
        flexDirection: 'row !important',
        margin: '0px auto !important',
        [theme.breakpoints.down('md')]: {
            justifyContent: 'space-around !important',
        },
        [theme.breakpoints.down('sm')]: {
            flexDirection: 'column !important',
        },
    },
    formAdWrap: {
        height: 'fit-content !important',
        width: '100% !important',
        display: 'flex !important',
        flexDirection: 'column !important',
    },
    heading: {
        padding: '8px !important',
        fontSize: '26px !important',
        fontWeight: '500 !important',
        color: '#282828 !important',
        backgroundColor: '#e2e2e2 !important',
        [theme.breakpoints.down('md')]: {
            fontSize: '24px !important',
        },
        [theme.breakpoints.down('xs')]: {
            fontSize: '22px !important',
        },
    },
    content: {
        fontWeight: '500 !important',
        margin: '6px !important',
        border: '1px solid #aaaaaa !important',
        borderRadius: '6px !important',
        padding: '24px !important',
        fontSize: '16px !important',
        flexGrow: '1 !important',
        letterSpacing: '0.8px !important',
        display: 'flex !important',
        flexDirection: 'column !important',
        backgroundColor: '#e8e8e8 !important',
    },
    createRoomBox: {
        maxWidth: '650px !important',
        borderRadius: '4px !important',
        width: '40% !important',
        marginLeft: '4px !important',
        marginRight: '4px !important',
        backgroundColor: '#e2e2e2 !important',
        display: 'flex !important',
        flexDirection: 'column !important',
        [theme.breakpoints.down('md')]: {
            width: '46% !important',
        },
        [theme.breakpoints.down('sm')]: {
            width: '100% !important',
        },
    },
    joinRoomBox: {
        maxWidth: '650px !important',
        marginLeft: '4px !important',
        marginRight: '4px !important',
        width: '40% !important',
        display: 'flex !important',
        flexDirection: 'column !important',
        backgroundColor: '#e2e2e2 !important',
        [theme.breakpoints.down('md')]: {
            width: '46% !important',
        },
        [theme.breakpoints.down('sm')]: {
            width: '100% !important',
        },
    },
    middleSpace: {
        display: 'block !important',
        height: '100% !important',
        [theme.breakpoints.down('lg')]: {
            width: '4vw !important',
        },
        [theme.breakpoints.up('lg')]: {
            width: '8vw !important',
        },
        [theme.breakpoints.down('md')]: {
            display: 'none !important',
        },
        [theme.breakpoints.down('sm')]: {
            width: '100% !important',
            height: '20px !important',
        },
    },
    publicRooms: {
        padding: '0px 3vw !important',
        width: '100% !important',
        boxSizing: 'border-box !important',
        backgroundColor: '#e2e2e2 !important',
        display: 'flex !important',
        flexDirection: 'row !important',
        [theme.breakpoints.down('sm')]: {
            flexDirection: 'column !important',
        },
    },
    publicAdWrap: {
        width: '100% !important',
        height: 'fit-content !important',
        display: 'flex !important',
        flexDirection: 'column !important',
        [theme.breakpoints.up('lg')]: {
            flexDirection: 'row !important',
            width: '90% !important',
            margin: '0px auto !important',
        },
    },
    publicRoomsContent: {
        width: '100% !important',
        backgroundColor: '#e2e2e2 !important',
    },
    cardGroup: {
        width: '100% !important',
        flexWrap: 'wrap !important',
        display: 'flex !important',
        justifyContent: 'space-around !important',
    },
    roomCard: {
        height: '30vw !important',
        marginTop: '20px !important',
        marginBottom: '20px !important',
        width: '30vw !important',
        borderRadius: '6px !important',
        display: 'flex !important',
        border: '1px solid #aaaaaa !important',
        flexDirection: 'column !important',
        backgroundColor: '#e8e8e8 !important',
        overflow: 'hidden !important',
        [theme.breakpoints.down('sm')]: {
            width: '45vw !important',
            height: '45vw !important',
        },
        [theme.breakpoints.down('xs')]: {
            width: '90vw !important',
            height: '90vw !important',
        },
    },
    textCenter: {
        textAlign: 'center !important',
    },
    separator: {
        margin: '40px auto !important',
        width: '90% !important',
        height: '2px !important',
        borderRadius: '2px !important',
        backgroundColor: '#cccccc !important',
    },
    listContent: {
        padding: '4px !important',
        color: '#484848 !important',
        lineHeight: '1.6 !important',
        letterSpacing: '0.6px !important',
        fontWeight: '400 !important',
        [theme.breakpoints.up('lg')]: {
            fontSize: '16px !important',
        },
        [theme.breakpoints.down('lg')]: {
            fontSize: '14px !important',
        },
        [theme.breakpoints.down('sm')]: {
            marginLeft: '-10px !important',
            fontSize: '13px !important',
            letterSpacing: '0.5px !important',
        },
    },
    buttonRoom: {
        position: 'relative !important',
        letterSpacing: '0.5px !important',
        marginTop: '16px !important',
        '&:hover': {
            backgroundColor: '#282828 !important',
            color: '#e2e2e2 !important',
        },
    },
    formRoom: {
        position: 'relative !important',
        paddingTop: '26px !important',
        paddingLeft: '30px !important',
        paddingBottom: '20px !important',
        boxSizing: 'border-box !important',
    },
    checkbox: {
        margin: '2px 8px 0px 8px !important',
        [theme.breakpoints.down('xs')]: {
            margin: '2px 0px 0px -10px !important',
        },
    },
    publicImageDiv: {
        width: '100% !important',
        flexGrow: '1 !important',
        overflow: 'hidden !important',
        marginTop: '-30px !important',
        backgroundColor: '#e2e2e2 !important',
        boxSizing: 'border-box !important',
        borderBottom: '1px solid #aaaaaa !important',
    },
    publicImage: {
        width: '100% !important',
        height: '100% !important',
        objectFit: 'cover !important',
    },
    publicBottomDiv: {
        position: 'relative !important',
        height: '60px !important',
        display: 'flex !important',
        width: '100% !important',
        boxSizing: 'border-box !important',
        alignItems: 'center !important',
        justifyContent: 'space-between !important',
    },
    publicDescDiv: {
        display: 'flex !important',
        paddingLeft: '12px !important',
        letterSpacing: '0.4px !important',
        boxSizing: 'border-box !important',
    },
    publicBtnDiv: {
        display: 'flex !important',
        alignItems: 'center !important',
        marginRight: '12px !important',
        boxSizing: 'border-box !important',
    },
    publicBtn: {
        letterSpacing: '0.5px !important',
        width: '80px !important',
        '&:hover': {
            backgroundColor: '#282828 !important',
            color: '#e2e2e2 !important',
        },
    },
    publicOnline: {
        position: 'relative !important',
        left: '-8px !important',
        height: '30px !important',
        width: '70px !important',
        overflow: 'hidden !important',
        display: 'flex !important',
        alignItems: 'center !important',
        justifyContent: 'center !important',
        color: '#282828 !important',
        zIndex: '10 !important',
        transform: 'skew(-30deg) !important',
        backgroundColor: '#e2e2e2 !important',
        borderBottom: '1px solid #aaaaaa !important',
        borderRight: '1px solid #aaaaaa !important',
    },
    publicOnlineDiv: {
        transform: 'skew(30deg) !important',
        paddingLeft: '30px !important',
        display: 'flex !important',
        alignItems: 'center !important',
    },
    userIcon: {
        position: 'absolute !important',
        fontSize: '14px !important',
        left: '10px !important',
    },
    publicErrorDiv: {
        width: '70% !important',
        borderRadius: '6px !important',
        border: '1px solid #aaaaaa !important',
        margin: '25px auto !important',
        padding: '30px !important',
        boxSizing: 'border-box !important',
        fontSize: '18px !important',
        backgroundColor: '#e8e8e8 !important',
        display: 'flex !important',
        alignItems: 'center !important',
        justifyContent: 'center !important',
        color: '#585858 !important',
        letterSpacing: '0.4px !important',
        fontWeight: '500 !important',
        [theme.breakpoints.down('sm')]: {
            padding: '20px !important',
            width: '80% !important',
        },
        [theme.breakpoints.down('xs')]: {
            fontSize: '16px !important',
            padding: '25px !important',
            width: '90% !important',
        },
    },
    errorIcon: {
        fontSize: '24px !important',
        color: '#888888 !important',
        margin: '0px 15px 0px -10px !important',
    },
    adBlock: {
        margin: '20px auto !important',
        boxSizing: 'border-box !important',
        width: '84% !important',
        display: 'none !important',
        height: '300px !important',
        backgroundColor: '#e8e8e8 !important',
        borderRadius: '4px !important',
        border: '1px solid #aaaaaa !important',
        [theme.breakpoints.down('sm')]: {
            width: '90% !important',
        },
    },
    createErrorDiv: {
        position: 'fixed !important',
        top: '200px !important',
        zIndex: '100 !important',
        maxWidth: '100% !important',
        width: 'fit-content !important',
        marginTop: '4px !important',
        padding: '8px !important',
        border: '1px solid #d0b8b8 !important',
        backgroundColor: '#f0d8d8 !important',
        color: '#484848 !important',
        letterSpacing: '0.4px !important',
        borderRadius: '2px !important',
        fontSize: '14px !important',
        fontWeight: '400 !important',
        display: 'none !important',
    },
    joinErrorDiv: {
        position: 'fixed !important',
        top: '200px !important',
        zIndex: '100 !important',
        maxWidth: '100% !important',
        width: 'fit-content !important',
        marginTop: '4px !important',
        padding: '8px !important',
        border: '1px solid #d0b8b8 !important',
        backgroundColor: '#f0d8d8 !important',
        color: '#484848 !important',
        letterSpacing: '0.4px !important',
        borderRadius: '2px !important',
        fontSize: '14px !important',
        fontWeight: '400 !important',
        display: 'none !important',
    },
}));
