import { makeStyles } from '@mui/styles/index.js';

export default makeStyles((theme) => ({
    mainContainer: {
        position: 'absolute !important',
        left: '0 !important',
        zIndex: '20 !important',
        width: '100% !important',
        height: '100vh !important',
    },
    overlay: {
        position: 'absolute !important',
        width: '100% !important',
        height: '100% !important',
        backgroundColor: '#e2e2e2 !important',
        opacity: '0.8 !important',
    },
    centered: {
        position: 'absolute !important',
        top: '50% !important',
        left: '50% !important',
        boxShadow: '0px 1px 4px #888888 !important',
        borderRadius: '6px !important',
        boxSizing: 'border-box !important',
        backgroundColor: '#e8e8e8 !important',
        transform: 'translate(-50%, -50%) !important',
    },
    header: {
        width: '100% !important',
        padding: '10px 20px !important',
        boxSizing: 'border-box !important',
        borderBottom: '1px solid #aaaaaa !important',
        fontSize: '20px !important',
        fontWeight: '500 !important',
    },
    selectDiv: {
        width: '100% !important',
        display: 'flex !important',
        justifyContent: 'center !important',
    },
    statusEditDiv: {
        padding: '20px !important',
        alignItems: 'center !important',
        display: 'flex !important',
        boxSizing: 'border-box !important',
        width: '100% !important',
        justifyContent: 'center !important',
    },
    aboutEditDiv: {
        padding: '20px !important',
        alignItems: 'center !important',
        display: 'flex !important',
        boxSizing: 'border-box !important',
        width: '100% !important',
        justifyContent: 'center !important',
    },
    select: {
        width: '150px !important',
        margin: '30px 0px !important',
        boxSizing: 'border-box !important',
    },
    statusInput: {
        width: '100% !important',
        height: '60px !important',
        minWidth: '200px !important',
        fontSize: '16px !important',
        border: '1px solid #aaaaaa !important',
        outline: 'none !important',
        padding: '8px !important',
        borderRadius: '4px !important',
        '&:hover &:active': {
            border: 'none !important',
            outline: 'none !important',
        },
    },
    aboutInput: {
        width: '400px !important',
        minWidth: '200px !important',
        height: '120px !important',
        border: '1px solid #aaaaaa !important',
        fontSize: '16px !important',
        padding: '8px !important',
        outline: 'none !important',
        borderRadius: '4px !important',
        [theme.breakpoints.down('xs')]: {
            width: '100% !important',
        },
        '&:hover &:active': {
            border: 'none !important',
            outline: 'none !important',
        },
    },
    buttonDiv: {
        padding: '0px 0px 20px 0px !important',
        width: '300px !important',
        maxWidth: '90vw !important',
        display: 'flex !important',
        justifyContent: 'space-around !important',
    },
    buttonSave: {
        width: '40% !important',
        backgroundColor: '#282828 !important',
        color: '#e2e2e2 !important',
        '&:hover': {
            backgroundColor: '#383838 !important',
            color: '#e2e2e2 !important',
        },
    },
    buttonCancel: {
        width: '40% !important',
        backgroundColor: '#e2e2e2 !important',
        color: '#282828 !important',
    },
    menuPaper: {
        maxHeight: '200px !important',
    },
    closeEdit: {
        position: 'absolute !important',
        top: '0% !important',
        right: '0% !important',
        display: 'flex !important',
        alignItems: 'center !important',
        borderRadius: '4px !important',
        boxSizing: 'border-box !important',
        opacity: '0.4 !important',
        color: '#282828 !important',
    },
    closeIcon: {
        fontSize: '26px !important',
        padding: '6px 10px !important',
        '&:hover': {
            cursor: 'pointer !important',
            transform: 'scale(1.1,1.1) !important',
        },
    },
}));
