import { makeStyles } from '@mui/styles/index.js';

export default makeStyles((theme) => ({
    button: {
        marginLeft: '15px !important',
        padding: '4px 12px !important',
        backgroundColor: '#e8e8e8 !important',
        '&:hover': {
            backgroundColor: '#e8e8e8 !important',
            transform: 'scale(0.98, 0.98) !important',
        },
    },
    appBar: {
        display: 'flex !important',
        flexDirection: 'row !important',
        alignItems: 'center !important',
        zIndex: '100 !important',
        backgroundColor: '#282828 !important',
    },
    toolbar: {
        marginLeft: 'auto !important',
        display: 'flex !important',
    },
    brandContainer: {
        marginLeft: '30px !important',
        display: 'flex !important',
        alignItems: 'center !important',
        float: 'left !important',
    },
    image: {
        marginTop: '4px !important',
        height: "40px !important",
        backgroundColor: '#282828 !important',
        [theme.breakpoints.down('sm')]: {
            //height: "36px",
            marginTop: '0px !important',
        },
    },
    brandName: {
        fontFamily: 'Anaheim !important',
        fontWeight: '600 !important',
        color: '#e2e2e2 !important',
        letterSpacing: '3px !important',
        fontSize: '20px !important',
        marginLeft: '16px !important',
        marginRight: '50px !important',
        textDecoration: 'none !important',
        alignSelf: 'flex-end !important',
        marginBottom: '14px !important',
        [theme.breakpoints.down('sm')]: {
            display: 'none !important',
        },
    },
    displayMobile: {
        width: '200px !important',
        padding: '18px 12px !important',
        margin: '20px 0px 10px 0px !important',
        boxShadow: 'none !important',
        backgroundColor: '#e2e2e2 !important',
        [theme.breakpoints.down('xs')]: {
            display: 'flex !important',
        },
    },
    hideMobile: {
        backgroundColor: '#e8e8e8 !important',
        width: '240px !important',
        marginLeft: '30px !important',
        padding: '0px 12px !important',
        [theme.breakpoints.down('xs')]: {
            display: 'none !important',
        },
    },
    searchBar: {
        position: 'relative !important',
        height: '32px !important',
        fontSize: '16px !important',
        borderWidth: '0 !important',
        boxSizing: 'border-box !important',
        outline: 'none !important',
        borderRadius: '4px !important',
        '&:hover,&:focus': {
            transform: 'scale(0.99,0.98) !important',
        },
        [theme.breakpoints.down('xs')]: {
            fontSize: '15px !important',
        },
    },
    searchResult: {
        position: 'absolute !important',
        top: '50px !important',
        borderRadius: '4px !important',
        height: 'fit-content !important',
        width: '240px !important',
        display: 'none !important',
        overflow: 'hidden !important',
        boxShadow: '0px 0px 4px #aaaaaa !important',
        boxSizing: 'border-box !important',
        backgroundColor: '#e8e8e8 !important',
    },
    searchResult2: {
        borderRadius: '4px !important',
        height: 'fit-content !important',
        width: '200px !important',
        display: 'none !important',
        overflow: 'hidden !important',
        boxSizing: 'border-box !important',
        backgroundColor: '#e8e8e8 !important',
    },
    userListItem: {
        width: '100% !important',
        height: '50px !important',
        borderBottom: '2px solid #dddddd !important',
        boxSizing: 'border-box !important',
        alignItems: 'center !important',
        display: 'flex !important',
        flexDirection: 'row !important',
        '&:hover': {
            cursor: 'pointer !important',
        },
    },
    userListAvatar: {
        height: '30px !important',
        width: '30px !important',
        borderRadius: '17px !important',
        margin: '0px 8px !important',
        border: '2px solid #cccccc !important',
    },
    userListName: {
        flexGrow: '1 !important',
        fontSize: '14px !important',
        textOverflow: 'ellipsis !important',
        whiteSpace: 'nowrap !important',
        overflow: 'hidden !important',
        fontWeight: '500 !important',
        color: '#282828 !important',
    },
    noUserError: {
        color: '#383838 !important',
        display: 'flex !important',
        fontSize: '14px !important',
        alignItems: 'center !important',
        fontWeight: '500 !important',
    },
    errorIcon: {
        fontSize: '20px !important',
        color: '#686868 !important',
        margin: '0px 10px 0px 20px !important',
    },
    navTab: {
        color: 'white !important',
        display: 'none !important',
        marginLeft: '30px !important',
        textDecorationLine: 'none !important',
        [theme.breakpoints.down('sm')]: {
            display: 'none !important',
        },
    },
    drawerBtn: {
        marginLeft: '15px !important',
        height: '40px !important',
        width: '40px !important',
        display: 'flex !important',
        justifyContent: 'center !important',
        alignItems: 'center !important',
    },
    optionBtn: {
        display: 'none !important',
        marginLeft: '15px !important',
        height: '40px !important',
        width: '40px !important',
        justifyContent: 'center !important',
        alignItems: 'center !important',
        [theme.breakpoints.down('xs')]: {
            display: 'flex !important',
        },
    },
    optionDiv: {
        display: 'none !important',
        position: 'fixed !important',
        width: '240px !important',
        minWidth: 'fit-content !important',
        right: '0px !important',
        top: '64px !important',
        flexDirection: 'column !important',
        boxShadow: '2px 0px 16px #282828 !important',
        boxSizing: 'border-box !important',
        alignItems: 'center !important',
        padding: '4px 6px !important',
        zIndex: '21 !important',
        height: '100vh !important',
        backgroundColor: '#282828 !important',
        [theme.breakpoints.down('xs')]: {
            top: '56px !important',
        },
    },
    icon: {
        fontSize: '24px !important',
        color: '#e8e8e8 !important',
        userSelect: 'none !important',
        '&:hover': {
            cursor: 'pointer !important',
        },
    },
    avatar: {
        backgroundColor: '#e2e2e2 !important',
        marginLeft: '15px !important',
        height: '24px !important',
        width: '24px !important',
        border: '2px solid #555555 !important',
        '&:hover': {
            cursor: 'pointer !important',
        },
    },
    chatFrame: {
        boxShadow: '4px 0px 20px #282828 !important',
        position: 'fixed !important',
        display: 'none !important',
        right: '0px !important',
        top: '0px !important',
        width: '80vw !important',
        maxWidth: '500px !important',
        height: '100% !important',
        backgroundColor: 'violet !important',
        zIndex: '20 !important',
    },
    profileOptionsDiv: {
        display: 'none !important',
        position: 'absolute !important',
        height: 'fit-content !important',
        width: '100px !important',
        boxShadow: '0px 0px 4px #585858 !important',
        fontSize: '14px !important',
        flexDirection: 'column !important',
        backgroundColor: '#e8e8e8 !important',
        color: '#282828 !important',
        top: '64px !important',
        right: '60px !important',
        [theme.breakpoints.down('xs')]: {
            top: '56px !important',
            right: '50px !important',
        },
    },
    profileOptionItem: {
        width: '100% !important',
        boxSizing: 'border-box !important',
        padding: '8px 12px !important',
        '&:hover': {
            cursor: 'pointer !important',
            backgroundColor: '#dddddd !important',
        },
    },
    profileOptionDivider: {
        width: '100% !important',
        backgroundColor: '#aaaaaa !important',
        height: '1px !important',
    },
    arrowTriangle: {
        position: 'absolute !important',
        top: '-8px !important',
        right: '28px !important',
        height: '0px !important',
        width: '0px !important',
        borderLeft: '6px solid transparent !important',
        borderRight: '6px solid transparent !important',
        borderBottom: '8px solid #e2e2e2 !important',
    },
    clearIcon: {
        position: 'relative !important',
        marginLeft: '-28px !important',
        fontSize: '20px !important',
        padding: '5px 6px !important',
        boxSizing: 'border-box !important',
        color: '#aaaaaa !important',
        '&:hover': {
            cursor: 'pointer !important',
            transform: 'scale(1.1,1.1) !important',
        },
        [theme.breakpoints.down('xs')]: {
            display: 'none !important',
        },
    },
    clearIconMobile: {
        position: 'absolute !important',
        top: '36% !important',
        right: '0px !important',
        fontSize: '18px !important',
        padding: '5px 6px !important',
        boxSizing: 'border-box !important',
        color: '#888888 !important',
        '&:hover': {
            cursor: 'pointer !important',
        },
    },
    searchMobileDiv: {
        position: 'relative !important',
        display: 'flex !important',
    },
}));
